config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get "u/:username" => "public#profile", as: :profile

  resources :communities do
    resources :posts
  end

  resources :subscriptions
  resources :comments, only: [:create]

  root to: "public#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable         
  
  has_many :communities, through: :subscriptions
  has_many :posts
  has_many :comments

  validates_presence_of :first_name, :last_name, :username

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :account

    validates_presence_of :message, :account_id, :post_id
end

app/models/community.rb
class Community < ApplicationRecord
    belongs_to :account
    validates_presence_of :url, :name, :rules
    has_many :posts
    has_many :subscriptions
    has_many :subscribers, through: :subscriptions, source: :account

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :account
    belongs_to :community
    validates_presence_of :title, :body, :account_id, :community_id
    has_many :comments
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :account
    belongs_to :community
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    skip_before_action :verify_authenticity_token
    
    def create
        @comment = Comment.new(comment_params)
        @comment.account_id = current_account.id

        respond_to do |format|
            if @comment.save
                @comments = Comment.where(post_id: @comment.post_id)
                format.js { render "comments/create" }
            else
                # unable to save
            end
        end
    end

    def comment_params
        params.require(:comment).permit(:message, :post_id)
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
    before_action :authenticate_account!, except: [ :index, :show ]
    before_action :set_community, only: [:show]

    def index
        @communities = Community.all
    end
    
    def show
        @posts = @community.posts
        @subscriber_count = @community.subscribers.count
        @is_subscribed = account_signed_in? ? Subscription.where(community_id: @community.id, account_id: current_account.id).any? : false
        @subscription = Subscription.new
    end

    def new
        @community = Community.new
    end

    def create
        @community = Community.new(community_values)
        @community.account_id = current_account.id

        if @community.save
            redirect_to communities_path
        else
            render :new
        end
    end

    private

    def set_community
        @community = Community.find(params[:id])
    end

    def community_values
        params.require(:community).permit(:name, :url, :summary, :rules)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_account!, except: [ :index, :show ]
    before_action :set_post, only: [:show]
    before_action :auth_subscriber, only: [:new]

    def index
        @posts = Post.all
    end

    def show
        @comment = Comment.new
    end

    def new
        @community = Community.find(params[:community_id])
        @post = Post.new
    end

    def create
        @post = Post.new(post_values)
        @post.account_id = current_account.id
        @post.community_id = params[:community_id]

        if @post.save
            redirect_to community_path(@post.community_id)
        else
            @community = Community.find(params[:community_id])
            render :new
        end
    end

    private

    def set_post
        @post = Post.includes(:comments).find(params[:id])
    end

    def auth_subscriber
        unless Subscription.where(community_id: params[:community_id], account_id: current_account.id).any?
            redirect_to root_path, flash: { danger: "You are not authorized to view this page" }
        end
    end

    def post_values
        params.require(:post).permit(:title, :body)
    end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

    def index
        @communities = Community.all.limit(5)
        @posts = Post.order(id: :desc).limit(20)
    end

    def profile
        @profile = Account.find_by_username params[:username]
        @posts = @profile.posts
    end
    
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
    def create
        @subscription = Subscription.new(subscription_params)
        @subscription.account_id = current_account.id
        @subscription.save
        
        redirect_to community_path(@subscription.community_id)
    end

    def subscription_params
        params.require(:subscription).permit(:community_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.js.erb
console.log("comment created...");

$("#post-comments").html("<%= escape_javascript(render partial: 'posts/comments', locals: { comments: @comments }) %>");

app/views/communities/_form.html.erb
<div class="row">
    <div class="col-sm-6">
        <%= form_for @community do |form| %>
            <div class="mb-3">
                <%= label_tag :name %>
                <%= form.text_field :name, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= label_tag :url %>
                <%= form.text_field :url, class: "form-control" %>
            </div>            
            <div class="mb-3">
                <%= label_tag :summary %>
                <%= form.text_field :summary, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= label_tag :rules %>
                <%= form.text_area :rules, class: "form-control" %>
            </div>
            <%= form.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f| %>
    <%= f.hidden_field :community_id, value: community_id %>
    <%= f.submit "Join Community", class: "btn btn-success text-uppercase float-end" %>
<% end %>

app/views/communities/index.html.erb
<% if account_signed_in? %>
    <div class="float-end">
        <%= link_to "Create New Community", new_community_path, class: "btn btn-outline-primary" %>
    </div>
<% end %>



<% if @communities.size > 0%>
    <% @communities.each do |community| %>
        <div class="card">
            <h3><%= link_to community.name, community %></h3>
            <%= simple_format community.rules %>
        </div>
    <% end %>
<% else %>
    <p>No communities to display.</p>
<% end %>

app/views/communities/new.html.erb
<h2>New Community</h2>

<%= render partial: "form" %>

app/views/communities/show.html.erb
<div class="row mb-4">
    <div class="col-sm-8">
        <h3><%= @community.name %></h3>    
    </div>
    <div class="col-sm-4">
        <% if @is_subscribed %>
            <%= link_to "Create New Post", new_community_post_path(@community), class: "btn btn-primary float-end" %>
        <% else %>
            <%= render partial: "communities/subscribe", locals: { community_id: @community.id } %>
        <% end %>
    </div>
</div>



<div class="row">
    <div class="col-sm-8">
        <%= render partial: "posts/list", locals: { posts: @posts } %>
    </div>
    <div class="col-sm-4">
        <div class="card p-3">
            <p class="h5">About this community</p>
            <p class="mt-2"><%= @community.summary %></p>
            <p><%= pluralize @subscriber_count, "member" %></p>
        </div>
        <small>
            <%= simple_format @community.rules %>
        </small>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="container">
    <div class="row">
        <div class="col-12 pt-3 pb-4">
            <div class="float-end">
                <% if account_signed_in? %>
                <div class="dropdown">
                    <a class="btn btn-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        <%= current_account.full_name %>
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <%= link_to "Profile", profile_path(current_account.username), method: :get, class: "dropdown-item" %>
                        <%= link_to "Settings", edit_account_registration_path, method: :get, class: "dropdown-item" %>
                        <%= button_to "Sign Out", destroy_account_session_path, method: :delete, class: "dropdown-item" %>
                    </ul>
                </div>
                <% else %>
                    <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
                    <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-primary" %>
                <% end %>
            </div>
            <p class="h3"><%= link_to "Reddit Clone", root_path %></p>
        </div>
     </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
    <script defer src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: "layouts/header" %>

    <section class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 pt-4">
            <%= yield %>
          </div>      
        </div>
      </div>
    </section>


    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/posts/_comments.html.erb
<% comments.each do |comment| %>
    <div>
        <%= link_to comment.account.full_name, profile_path(comment.account.username) %>
        <%= simple_format comment.message %>
    </div>
<% end %>

app/views/posts/_form.html.erb
<div class="row">
    <div class="col-sm-6">
        <%= form_for [@community, @post] do |form| %>
            <div class="mb-3">
                <%= label_tag :title %>
                <%= form.text_field :title, class: "form-control" %>
            </div>          
            <div class="mb-3">
                <%= label_tag :body %>
                <%= form.text_area :body, class: "form-control" %>
            </div>
            <%= form.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/posts/_list.html.erb
<% @posts.each do |post| %>
    <div class="card p-3">
        <h4 class="mb-1"><%= link_to post.title, community_post_path(post.community_id, post) %></h4>
        <p><small><%= link_to post.community.name, community_path(post.community) %> Posted by <%= link_to post.account.full_name, profile_path(post.account.username) %> <%= time_ago_in_words post.created_at %> ago.</small></p>
        <p><%= truncate post.body, length: 200 %></p>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<%= simple_format @post.body %>

<div id="post-comments">
    <%= render partial: "posts/comments", locals: { comments: @post.comments } %>
</div>

<h5>Leave a comment</h5>
<%= form_for @comment, remote: true do |f| %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.text_area :message, placeholder: "Your comment goes here", class: "form-control" %>
    <%= f.submit "Submit comment", class: "btn btn-success mt-3" %>
<% end %>